// This file was generated by Conjure and should not be manually edited.

//go:build go1.18

package barfoo

import (
	"context"
	"fmt"
)

type FooType3WithT[T any] FooType3

func (u *FooType3WithT[T]) Accept(ctx context.Context, v FooType3VisitorWithT[T]) (T, error) {
	switch u.typ {
	default:
		if u.typ == "" {
			var result T
			return result, fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknown(ctx, u.typ)
	case "field1":
		return v.VisitField1(ctx, *u.field1)
	case "field3":
		return v.VisitField3(ctx, *u.field3)
	}
}

type FooType3VisitorWithT[T any] interface {
	VisitField1(ctx context.Context, v Type2) (T, error)
	VisitField3(ctx context.Context, v Type1) (T, error)
	VisitUnknown(ctx context.Context, typ string) (T, error)
}
