// Code generated by conjure-go. DO NOT EDIT.

package server

import (
	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
	"github.com/palantir/conjure-go/v6/cj"
	"github.com/palantir/conjure-go/v6/cj/types"
)

type ClientTestCases struct {
	AutoDeserialize         map[EndpointName]PositiveAndNegativeTestCases `json:"autoDeserialize"`
	SingleHeaderService     map[EndpointName][]string                     `json:"singleHeaderService"`
	SinglePathParamService  map[EndpointName][]string                     `json:"singlePathParamService"`
	SingleQueryParamService map[EndpointName][]string                     `json:"singleQueryParamService"`
}

func (o ClientTestCases) MarshalJSON() ([]byte, error) {
	return cj.Marshal[ClientTestCases, types.StructMarshaler[ClientTestCases]](o)
}

func (o ClientTestCases) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	{
		if err := enc.WriteToken(jsontext.String("autoDeserialize")); err != nil {
			return err
		}
		if err := cj.MarshalEncode[map[EndpointName]PositiveAndNegativeTestCases, types.OrderedMapMarshaler[map[EndpointName]PositiveAndNegativeTestCases, EndpointName, PositiveAndNegativeTestCases, types.String[EndpointName], types.StructMarshaler[PositiveAndNegativeTestCases]]](enc, o.AutoDeserialize); err != nil {
			return err
		}
	}
	{
		if err := enc.WriteToken(jsontext.String("singleHeaderService")); err != nil {
			return err
		}
		if err := cj.MarshalEncode[map[EndpointName][]string, types.OrderedMapMarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListMarshaler[[]string, string, types.String[string]]]](enc, o.SingleHeaderService); err != nil {
			return err
		}
	}
	{
		if err := enc.WriteToken(jsontext.String("singlePathParamService")); err != nil {
			return err
		}
		if err := cj.MarshalEncode[map[EndpointName][]string, types.OrderedMapMarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListMarshaler[[]string, string, types.String[string]]]](enc, o.SinglePathParamService); err != nil {
			return err
		}
	}
	{
		if err := enc.WriteToken(jsontext.String("singleQueryParamService")); err != nil {
			return err
		}
		if err := cj.MarshalEncode[map[EndpointName][]string, types.OrderedMapMarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListMarshaler[[]string, string, types.String[string]]]](enc, o.SingleQueryParamService); err != nil {
			return err
		}
	}
	if err := enc.WriteToken(jsontext.EndObject); err != nil {
		return err
	}
	return nil
}

func (o *ClientTestCases) UnmarshalJSON(data []byte) error {
	return cj.Unmarshal[ClientTestCases, types.StructUnmarshaler[*ClientTestCases]](data, o)
}

func (o *ClientTestCases) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var seenAutoDeserialize bool
	var seenSingleHeaderService bool
	var seenSinglePathParamService bool
	var seenSingleQueryParamService bool
	var unknownMembers []string
	if tok, err := dec.ReadToken(); err != nil {
		return err
	} else if kind := tok.Kind(); kind != '{' {
		return cj.NewKindMismatchError(dec, kind, "opening brace for ClientTestCases")
	}
	for {
		key, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if kind := key.Kind(); kind == '}' {
			break // End of object
		} else if kind != '"' {
			return cj.NewKindMismatchError(dec, kind, "ClientTestCases next key or closing brace")
		}
		switch key.String() {
		case "autoDeserialize":
			if seenAutoDeserialize {
				return cj.NewDuplicateFieldKeyError(dec, "ClientTestCases[\"autoDeserialize\"]")
			}
			if err := cj.UnmarshalDecode[map[EndpointName]PositiveAndNegativeTestCases, types.MapUnmarshaler[map[EndpointName]PositiveAndNegativeTestCases, EndpointName, PositiveAndNegativeTestCases, types.String[EndpointName], types.StructUnmarshaler[*PositiveAndNegativeTestCases]]](dec, &o.AutoDeserialize); err != nil {
				return cj.NewUnmarshalFieldError(dec, "ClientTestCases[\"autoDeserialize\"]", err)
			}
			seenAutoDeserialize = true
		case "singleHeaderService":
			if seenSingleHeaderService {
				return cj.NewDuplicateFieldKeyError(dec, "ClientTestCases[\"singleHeaderService\"]")
			}
			if err := cj.UnmarshalDecode[map[EndpointName][]string, types.MapUnmarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListUnmarshaler[[]string, string, types.String[string]]]](dec, &o.SingleHeaderService); err != nil {
				return cj.NewUnmarshalFieldError(dec, "ClientTestCases[\"singleHeaderService\"]", err)
			}
			seenSingleHeaderService = true
		case "singlePathParamService":
			if seenSinglePathParamService {
				return cj.NewDuplicateFieldKeyError(dec, "ClientTestCases[\"singlePathParamService\"]")
			}
			if err := cj.UnmarshalDecode[map[EndpointName][]string, types.MapUnmarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListUnmarshaler[[]string, string, types.String[string]]]](dec, &o.SinglePathParamService); err != nil {
				return cj.NewUnmarshalFieldError(dec, "ClientTestCases[\"singlePathParamService\"]", err)
			}
			seenSinglePathParamService = true
		case "singleQueryParamService":
			if seenSingleQueryParamService {
				return cj.NewDuplicateFieldKeyError(dec, "ClientTestCases[\"singleQueryParamService\"]")
			}
			if err := cj.UnmarshalDecode[map[EndpointName][]string, types.MapUnmarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListUnmarshaler[[]string, string, types.String[string]]]](dec, &o.SingleQueryParamService); err != nil {
				return cj.NewUnmarshalFieldError(dec, "ClientTestCases[\"singleQueryParamService\"]", err)
			}
			seenSingleQueryParamService = true
		default:
			unknownMembers = append(unknownMembers, key.String())
		}
	}
	if !seenAutoDeserialize {
		o.AutoDeserialize = make(map[EndpointName]PositiveAndNegativeTestCases)
	}
	if !seenSingleHeaderService {
		o.SingleHeaderService = make(map[EndpointName][]string)
	}
	if !seenSinglePathParamService {
		o.SinglePathParamService = make(map[EndpointName][]string)
	}
	if !seenSingleQueryParamService {
		o.SingleQueryParamService = make(map[EndpointName][]string)
	}
	if len(unknownMembers) > 0 {
		if strict, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); strict {
			return cj.NewUnknownFieldsError(dec, "ClientTestCases", unknownMembers)
		}
	}
	return nil
}

func (o ClientTestCases) MarshalYAML() (interface{}, error) {
	return cj.MarshalYAML(o)
}

func (o *ClientTestCases) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return cj.UnmarshalYAML(o, unmarshal)
}

type IgnoredClientTestCases struct {
	AutoDeserialize         map[EndpointName][]string `json:"autoDeserialize"`
	SingleHeaderService     map[EndpointName][]string `json:"singleHeaderService"`
	SinglePathParamService  map[EndpointName][]string `json:"singlePathParamService"`
	SingleQueryParamService map[EndpointName][]string `json:"singleQueryParamService"`
}

func (o IgnoredClientTestCases) MarshalJSON() ([]byte, error) {
	return cj.Marshal[IgnoredClientTestCases, types.StructMarshaler[IgnoredClientTestCases]](o)
}

func (o IgnoredClientTestCases) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	{
		if err := enc.WriteToken(jsontext.String("autoDeserialize")); err != nil {
			return err
		}
		if err := cj.MarshalEncode[map[EndpointName][]string, types.OrderedMapMarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListMarshaler[[]string, string, types.String[string]]]](enc, o.AutoDeserialize); err != nil {
			return err
		}
	}
	{
		if err := enc.WriteToken(jsontext.String("singleHeaderService")); err != nil {
			return err
		}
		if err := cj.MarshalEncode[map[EndpointName][]string, types.OrderedMapMarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListMarshaler[[]string, string, types.String[string]]]](enc, o.SingleHeaderService); err != nil {
			return err
		}
	}
	{
		if err := enc.WriteToken(jsontext.String("singlePathParamService")); err != nil {
			return err
		}
		if err := cj.MarshalEncode[map[EndpointName][]string, types.OrderedMapMarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListMarshaler[[]string, string, types.String[string]]]](enc, o.SinglePathParamService); err != nil {
			return err
		}
	}
	{
		if err := enc.WriteToken(jsontext.String("singleQueryParamService")); err != nil {
			return err
		}
		if err := cj.MarshalEncode[map[EndpointName][]string, types.OrderedMapMarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListMarshaler[[]string, string, types.String[string]]]](enc, o.SingleQueryParamService); err != nil {
			return err
		}
	}
	if err := enc.WriteToken(jsontext.EndObject); err != nil {
		return err
	}
	return nil
}

func (o *IgnoredClientTestCases) UnmarshalJSON(data []byte) error {
	return cj.Unmarshal[IgnoredClientTestCases, types.StructUnmarshaler[*IgnoredClientTestCases]](data, o)
}

func (o *IgnoredClientTestCases) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var seenAutoDeserialize bool
	var seenSingleHeaderService bool
	var seenSinglePathParamService bool
	var seenSingleQueryParamService bool
	var unknownMembers []string
	if tok, err := dec.ReadToken(); err != nil {
		return err
	} else if kind := tok.Kind(); kind != '{' {
		return cj.NewKindMismatchError(dec, kind, "opening brace for IgnoredClientTestCases")
	}
	for {
		key, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if kind := key.Kind(); kind == '}' {
			break // End of object
		} else if kind != '"' {
			return cj.NewKindMismatchError(dec, kind, "IgnoredClientTestCases next key or closing brace")
		}
		switch key.String() {
		case "autoDeserialize":
			if seenAutoDeserialize {
				return cj.NewDuplicateFieldKeyError(dec, "IgnoredClientTestCases[\"autoDeserialize\"]")
			}
			if err := cj.UnmarshalDecode[map[EndpointName][]string, types.MapUnmarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListUnmarshaler[[]string, string, types.String[string]]]](dec, &o.AutoDeserialize); err != nil {
				return cj.NewUnmarshalFieldError(dec, "IgnoredClientTestCases[\"autoDeserialize\"]", err)
			}
			seenAutoDeserialize = true
		case "singleHeaderService":
			if seenSingleHeaderService {
				return cj.NewDuplicateFieldKeyError(dec, "IgnoredClientTestCases[\"singleHeaderService\"]")
			}
			if err := cj.UnmarshalDecode[map[EndpointName][]string, types.MapUnmarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListUnmarshaler[[]string, string, types.String[string]]]](dec, &o.SingleHeaderService); err != nil {
				return cj.NewUnmarshalFieldError(dec, "IgnoredClientTestCases[\"singleHeaderService\"]", err)
			}
			seenSingleHeaderService = true
		case "singlePathParamService":
			if seenSinglePathParamService {
				return cj.NewDuplicateFieldKeyError(dec, "IgnoredClientTestCases[\"singlePathParamService\"]")
			}
			if err := cj.UnmarshalDecode[map[EndpointName][]string, types.MapUnmarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListUnmarshaler[[]string, string, types.String[string]]]](dec, &o.SinglePathParamService); err != nil {
				return cj.NewUnmarshalFieldError(dec, "IgnoredClientTestCases[\"singlePathParamService\"]", err)
			}
			seenSinglePathParamService = true
		case "singleQueryParamService":
			if seenSingleQueryParamService {
				return cj.NewDuplicateFieldKeyError(dec, "IgnoredClientTestCases[\"singleQueryParamService\"]")
			}
			if err := cj.UnmarshalDecode[map[EndpointName][]string, types.MapUnmarshaler[map[EndpointName][]string, EndpointName, []string, types.String[EndpointName], types.ListUnmarshaler[[]string, string, types.String[string]]]](dec, &o.SingleQueryParamService); err != nil {
				return cj.NewUnmarshalFieldError(dec, "IgnoredClientTestCases[\"singleQueryParamService\"]", err)
			}
			seenSingleQueryParamService = true
		default:
			unknownMembers = append(unknownMembers, key.String())
		}
	}
	if !seenAutoDeserialize {
		o.AutoDeserialize = make(map[EndpointName][]string)
	}
	if !seenSingleHeaderService {
		o.SingleHeaderService = make(map[EndpointName][]string)
	}
	if !seenSinglePathParamService {
		o.SinglePathParamService = make(map[EndpointName][]string)
	}
	if !seenSingleQueryParamService {
		o.SingleQueryParamService = make(map[EndpointName][]string)
	}
	if len(unknownMembers) > 0 {
		if strict, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); strict {
			return cj.NewUnknownFieldsError(dec, "IgnoredClientTestCases", unknownMembers)
		}
	}
	return nil
}

func (o IgnoredClientTestCases) MarshalYAML() (interface{}, error) {
	return cj.MarshalYAML(o)
}

func (o *IgnoredClientTestCases) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return cj.UnmarshalYAML(o, unmarshal)
}

type IgnoredTestCases struct {
	Client IgnoredClientTestCases `json:"client"`
}

func (o IgnoredTestCases) MarshalJSON() ([]byte, error) {
	return cj.Marshal[IgnoredTestCases, types.StructMarshaler[IgnoredTestCases]](o)
}

func (o IgnoredTestCases) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	{
		if err := enc.WriteToken(jsontext.String("client")); err != nil {
			return err
		}
		if err := cj.MarshalEncode[IgnoredClientTestCases, types.StructMarshaler[IgnoredClientTestCases]](enc, o.Client); err != nil {
			return err
		}
	}
	if err := enc.WriteToken(jsontext.EndObject); err != nil {
		return err
	}
	return nil
}

func (o *IgnoredTestCases) UnmarshalJSON(data []byte) error {
	return cj.Unmarshal[IgnoredTestCases, types.StructUnmarshaler[*IgnoredTestCases]](data, o)
}

func (o *IgnoredTestCases) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var seenClient bool
	var unknownMembers []string
	if tok, err := dec.ReadToken(); err != nil {
		return err
	} else if kind := tok.Kind(); kind != '{' {
		return cj.NewKindMismatchError(dec, kind, "opening brace for IgnoredTestCases")
	}
	for {
		key, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if kind := key.Kind(); kind == '}' {
			break // End of object
		} else if kind != '"' {
			return cj.NewKindMismatchError(dec, kind, "IgnoredTestCases next key or closing brace")
		}
		switch key.String() {
		case "client":
			if seenClient {
				return cj.NewDuplicateFieldKeyError(dec, "IgnoredTestCases[\"client\"]")
			}
			if err := cj.UnmarshalDecode[IgnoredClientTestCases, types.StructUnmarshaler[*IgnoredClientTestCases]](dec, &o.Client); err != nil {
				return cj.NewUnmarshalFieldError(dec, "IgnoredTestCases[\"client\"]", err)
			}
			seenClient = true
		default:
			unknownMembers = append(unknownMembers, key.String())
		}
	}
	var missingFields []string
	if !seenClient {
		missingFields = append(missingFields, "client")
	}
	if len(missingFields) > 0 {
		return cj.NewMissingFieldsError(dec, "IgnoredTestCases", missingFields)
	}
	if len(unknownMembers) > 0 {
		if strict, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); strict {
			return cj.NewUnknownFieldsError(dec, "IgnoredTestCases", unknownMembers)
		}
	}
	return nil
}

func (o IgnoredTestCases) MarshalYAML() (interface{}, error) {
	return cj.MarshalYAML(o)
}

func (o *IgnoredTestCases) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return cj.UnmarshalYAML(o, unmarshal)
}

type PositiveAndNegativeTestCases struct {
	Positive []string `json:"positive"`
	Negative []string `json:"negative"`
}

func (o PositiveAndNegativeTestCases) MarshalJSON() ([]byte, error) {
	return cj.Marshal[PositiveAndNegativeTestCases, types.StructMarshaler[PositiveAndNegativeTestCases]](o)
}

func (o PositiveAndNegativeTestCases) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	{
		if err := enc.WriteToken(jsontext.String("positive")); err != nil {
			return err
		}
		if err := cj.MarshalEncode[[]string, types.ListMarshaler[[]string, string, types.String[string]]](enc, o.Positive); err != nil {
			return err
		}
	}
	{
		if err := enc.WriteToken(jsontext.String("negative")); err != nil {
			return err
		}
		if err := cj.MarshalEncode[[]string, types.ListMarshaler[[]string, string, types.String[string]]](enc, o.Negative); err != nil {
			return err
		}
	}
	if err := enc.WriteToken(jsontext.EndObject); err != nil {
		return err
	}
	return nil
}

func (o *PositiveAndNegativeTestCases) UnmarshalJSON(data []byte) error {
	return cj.Unmarshal[PositiveAndNegativeTestCases, types.StructUnmarshaler[*PositiveAndNegativeTestCases]](data, o)
}

func (o *PositiveAndNegativeTestCases) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var seenPositive bool
	var seenNegative bool
	var unknownMembers []string
	if tok, err := dec.ReadToken(); err != nil {
		return err
	} else if kind := tok.Kind(); kind != '{' {
		return cj.NewKindMismatchError(dec, kind, "opening brace for PositiveAndNegativeTestCases")
	}
	for {
		key, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if kind := key.Kind(); kind == '}' {
			break // End of object
		} else if kind != '"' {
			return cj.NewKindMismatchError(dec, kind, "PositiveAndNegativeTestCases next key or closing brace")
		}
		switch key.String() {
		case "positive":
			if seenPositive {
				return cj.NewDuplicateFieldKeyError(dec, "PositiveAndNegativeTestCases[\"positive\"]")
			}
			if err := cj.UnmarshalDecode[[]string, types.ListUnmarshaler[[]string, string, types.String[string]]](dec, &o.Positive); err != nil {
				return cj.NewUnmarshalFieldError(dec, "PositiveAndNegativeTestCases[\"positive\"]", err)
			}
			seenPositive = true
		case "negative":
			if seenNegative {
				return cj.NewDuplicateFieldKeyError(dec, "PositiveAndNegativeTestCases[\"negative\"]")
			}
			if err := cj.UnmarshalDecode[[]string, types.ListUnmarshaler[[]string, string, types.String[string]]](dec, &o.Negative); err != nil {
				return cj.NewUnmarshalFieldError(dec, "PositiveAndNegativeTestCases[\"negative\"]", err)
			}
			seenNegative = true
		default:
			unknownMembers = append(unknownMembers, key.String())
		}
	}
	if !seenPositive {
		o.Positive = make([]string, 0)
	}
	if !seenNegative {
		o.Negative = make([]string, 0)
	}
	if len(unknownMembers) > 0 {
		if strict, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); strict {
			return cj.NewUnknownFieldsError(dec, "PositiveAndNegativeTestCases", unknownMembers)
		}
	}
	return nil
}

func (o PositiveAndNegativeTestCases) MarshalYAML() (interface{}, error) {
	return cj.MarshalYAML(o)
}

func (o *PositiveAndNegativeTestCases) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return cj.UnmarshalYAML(o, unmarshal)
}

type TestCases struct {
	Client ClientTestCases `json:"client"`
}

func (o TestCases) MarshalJSON() ([]byte, error) {
	return cj.Marshal[TestCases, types.StructMarshaler[TestCases]](o)
}

func (o TestCases) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	{
		if err := enc.WriteToken(jsontext.String("client")); err != nil {
			return err
		}
		if err := cj.MarshalEncode[ClientTestCases, types.StructMarshaler[ClientTestCases]](enc, o.Client); err != nil {
			return err
		}
	}
	if err := enc.WriteToken(jsontext.EndObject); err != nil {
		return err
	}
	return nil
}

func (o *TestCases) UnmarshalJSON(data []byte) error {
	return cj.Unmarshal[TestCases, types.StructUnmarshaler[*TestCases]](data, o)
}

func (o *TestCases) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var seenClient bool
	var unknownMembers []string
	if tok, err := dec.ReadToken(); err != nil {
		return err
	} else if kind := tok.Kind(); kind != '{' {
		return cj.NewKindMismatchError(dec, kind, "opening brace for TestCases")
	}
	for {
		key, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if kind := key.Kind(); kind == '}' {
			break // End of object
		} else if kind != '"' {
			return cj.NewKindMismatchError(dec, kind, "TestCases next key or closing brace")
		}
		switch key.String() {
		case "client":
			if seenClient {
				return cj.NewDuplicateFieldKeyError(dec, "TestCases[\"client\"]")
			}
			if err := cj.UnmarshalDecode[ClientTestCases, types.StructUnmarshaler[*ClientTestCases]](dec, &o.Client); err != nil {
				return cj.NewUnmarshalFieldError(dec, "TestCases[\"client\"]", err)
			}
			seenClient = true
		default:
			unknownMembers = append(unknownMembers, key.String())
		}
	}
	var missingFields []string
	if !seenClient {
		missingFields = append(missingFields, "client")
	}
	if len(missingFields) > 0 {
		return cj.NewMissingFieldsError(dec, "TestCases", missingFields)
	}
	if len(unknownMembers) > 0 {
		if strict, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); strict {
			return cj.NewUnknownFieldsError(dec, "TestCases", unknownMembers)
		}
	}
	return nil
}

func (o TestCases) MarshalYAML() (interface{}, error) {
	return cj.MarshalYAML(o)
}

func (o *TestCases) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return cj.UnmarshalYAML(o, unmarshal)
}
