// This file was generated by Conjure and should not be manually edited.

package api

import (
	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
	"github.com/palantir/conjure-go/v6/cj"
	"github.com/palantir/conjure-go/v6/cj/types"
)

type OptionalIntegerAlias struct {
	Value *int
}

func (a OptionalIntegerAlias) MarshalJSON() ([]byte, error) {
	return json.Marshal(json.MarshalerTo(a))
}

func (a OptionalIntegerAlias) MarshalJSONTo(enc *jsontext.Encoder) error {
	return (types.OptionalMarshaler[*int, int, types.Int32[int]]{}).MarshalJSONTo(enc, a.Value)
}

func (a *OptionalIntegerAlias) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, json.UnmarshalerFrom(a))
}

func (a *OptionalIntegerAlias) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	return (types.OptionalUnmarshaler[*int, int, types.Int32[int]]{}).UnmarshalJSONFrom(dec, &a.Value)
}

func (a OptionalIntegerAlias) MarshalYAML() (any, error) {
	return cj.YAMLV3MarshalerFromJSON(a)
}

func (a *OptionalIntegerAlias) UnmarshalYAML(unmarshal func(any) error) error {
	return cj.YAMLV3UnmarshalerToJSON(a, unmarshal)
}

type OptionalListAlias struct {
	Value *[]string
}

func (a OptionalListAlias) MarshalJSON() ([]byte, error) {
	return json.Marshal(json.MarshalerTo(a))
}

func (a OptionalListAlias) MarshalJSONTo(enc *jsontext.Encoder) error {
	return (types.OptionalMarshaler[*[]string, []string, types.ListMarshaler[[]string, string, types.String[string]]]{}).MarshalJSONTo(enc, a.Value)
}

func (a *OptionalListAlias) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, json.UnmarshalerFrom(a))
}

func (a *OptionalListAlias) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	return (types.OptionalUnmarshaler[*[]string, []string, types.ListUnmarshaler[[]string, string, types.String[string]]]{}).UnmarshalJSONFrom(dec, &a.Value)
}

func (a OptionalListAlias) MarshalYAML() (any, error) {
	return cj.YAMLV3MarshalerFromJSON(a)
}

func (a *OptionalListAlias) UnmarshalYAML(unmarshal func(any) error) error {
	return cj.YAMLV3UnmarshalerToJSON(a, unmarshal)
}

type StringAlias string

func (a StringAlias) String() string {
	return string(a)
}

func (a StringAlias) MarshalText() ([]byte, error) {
	return []byte(a), nil
}

func (a *StringAlias) UnmarshalText(data []byte) error {
	*a = StringAlias(data)
	return nil
}

func (a StringAlias) MarshalJSON() ([]byte, error) {
	return json.Marshal(json.MarshalerTo(a))
}

func (a StringAlias) MarshalJSONTo(enc *jsontext.Encoder) error {
	return (types.String[string]{}).MarshalJSONTo(enc, string(a))
}

func (a *StringAlias) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, json.UnmarshalerFrom(a))
}

func (a *StringAlias) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	return (types.String[string]{}).UnmarshalJSONFrom(dec, (*string)(a))
}

func (a StringAlias) MarshalYAML() (any, error) {
	return cj.YAMLV3MarshalerFromJSON(a)
}

func (a *StringAlias) UnmarshalYAML(unmarshal func(any) error) error {
	return cj.YAMLV3UnmarshalerToJSON(a, unmarshal)
}
