// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
	"github.com/palantir/conjure-go/v6/cj"
)

type CustomObject struct {
	Data []byte `json:"data"`
}

func (o CustomObject) MarshalJSON() ([]byte, error) {
	return cj.Marshal[CustomObject, cj.StructMarshaler[CustomObject]](o)
}

func (o CustomObject) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	{
		if err := enc.WriteToken(jsontext.String("data")); err != nil {
			return err
		}
		if err := cj.MarshalEncode[[]byte, cj.Binary[[]byte]](enc, o.Data); err != nil {
			return err
		}
	}
	if err := enc.WriteToken(jsontext.EndObject); err != nil {
		return err
	}
	return nil
}

func (o *CustomObject) UnmarshalJSON(data []byte) error {
	return cj.Unmarshal[CustomObject, cj.StructUnmarshaler[*CustomObject]](data, o)
}

func (o *CustomObject) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var seenData bool
	var unknownMembers []string
	if err := cj.VisitObjectFields(dec, func(key string, dec *jsontext.Decoder) error {
		switch key {
		case "data":
			if seenData {
				return cj.NewDuplicateFieldKeyError(dec, "CustomObject[\"data\"]")
			}
			if err := cj.UnmarshalDecode[[]byte, cj.Binary[[]byte]](dec, &o.Data); err != nil {
				return cj.NewUnmarshalFieldError(dec, "CustomObject[\"data\"]", err)
			}
			seenData = true
		default:
			unknownMembers = append(unknownMembers, key)
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		return err
	}
	var missingFields []string
	if !seenData {
		missingFields = append(missingFields, "data")
	}
	if len(missingFields) > 0 {
		return cj.NewMissingFieldsError(dec, "CustomObject", missingFields)
	}
	if len(unknownMembers) > 0 {
		if strict, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); strict {
			return cj.NewUnknownFieldsError(dec, "CustomObject", unknownMembers)
		}
	}
	return nil
}

func (o CustomObject) MarshalYAML() (interface{}, error) {
	return cj.MarshalYAML(o)
}

func (o *CustomObject) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return cj.UnmarshalYAML(o, unmarshal)
}
