// This file was generated by Conjure and should not be manually edited.

package api

import (
	"context"
	"fmt"

	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
	"github.com/palantir/conjure-go/v6/cj"
	"github.com/palantir/conjure-go/v6/cj/types"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

type CustomUnion struct {
	typ       string
	asString  *string
	asInteger *int
}

func (u CustomUnion) MarshalJSON() ([]byte, error) {
	return json.Marshal(json.MarshalerTo(u))
}

func (u CustomUnion) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String("type")); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String(u.typ)); err != nil {
		return err
	}
	switch u.typ {
	case "asString":
		if err := enc.WriteToken(jsontext.String("asString")); err != nil {
			return err
		}
		if u.asString != nil {
			if err := (types.String[string]{}).MarshalJSONTo(enc, *u.asString); err != nil {
				return err
			}
		} else {
			if err := enc.WriteToken(jsontext.Null); err != nil {
				return err
			}
		}
	case "asInteger":
		if err := enc.WriteToken(jsontext.String("asInteger")); err != nil {
			return err
		}
		if u.asInteger != nil {
			if err := (types.Int32[int]{}).MarshalJSONTo(enc, *u.asInteger); err != nil {
				return err
			}
		} else {
			if err := enc.WriteToken(jsontext.Null); err != nil {
				return err
			}
		}
	}
	if err := enc.WriteToken(jsontext.EndObject); err != nil {
		return err
	}
	return nil
}

func (u *CustomUnion) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, json.UnmarshalerFrom(u))
}

func (u *CustomUnion) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if tok, err := dec.ReadToken(); err != nil {
		return err
	} else if kind := tok.Kind(); kind != '{' {
		return cj.NewKindMismatchError(dec, kind, "opening brace for CustomUnion")
	}
	var seenType bool
	var seenAsString bool
	var seenAsInteger bool
	var unknownMembers []string
	for {
		key, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if kind := key.Kind(); kind == '}' {
			break // End of object
		} else if kind != '"' {
			return cj.NewKindMismatchError(dec, kind, "CustomUnion next key or closing brace")
		}
		switch key.String() {
		case "type":
			if seenType {
				return cj.NewDuplicateFieldKeyError(dec, "CustomUnion[\"type\"]")
			}
			if err := (types.String[string]{}).UnmarshalJSONFrom(dec, &u.typ); err != nil {
				return cj.NewUnmarshalFieldError(dec, "CustomUnion[\"type\"]", err)
			}
			seenType = true
		case "asString":
			if seenAsString {
				return cj.NewDuplicateFieldKeyError(dec, "CustomUnion[\"asString\"]")
			}
			u.asString = new(string)
			if err := (types.String[string]{}).UnmarshalJSONFrom(dec, u.asString); err != nil {
				return cj.NewUnmarshalFieldError(dec, "CustomUnion[\"asString\"]", err)
			}
			seenAsString = true
		case "asInteger":
			if seenAsInteger {
				return cj.NewDuplicateFieldKeyError(dec, "CustomUnion[\"asInteger\"]")
			}
			u.asInteger = new(int)
			if err := (types.Int32[int]{}).UnmarshalJSONFrom(dec, u.asInteger); err != nil {
				return cj.NewUnmarshalFieldError(dec, "CustomUnion[\"asInteger\"]", err)
			}
			seenAsInteger = true
		default:
			unknownMembers = append(unknownMembers, key.String())
		}
	}
	var missingFields []string
	if !seenType {
		missingFields = append(missingFields, "type")
	}
	if u.typ == "asString" && !seenAsString {
		missingFields = append(missingFields, "asString")
	}
	if u.typ == "asInteger" && !seenAsInteger {
		missingFields = append(missingFields, "asInteger")
	}
	if len(missingFields) > 0 {
		return cj.NewMissingFieldsError(dec, "CustomUnion", missingFields)
	}
	if len(unknownMembers) > 0 {
		if strict, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); strict {
			return cj.NewUnknownFieldsError(dec, "CustomUnion", unknownMembers)
		}
	}
	return nil
}

func (u CustomUnion) MarshalYAML() (any, error) {
	jsonBytes, err := safejson.Marshal(u)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (u *CustomUnion) UnmarshalYAML(unmarshal func(any) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&u)
}

func (u *CustomUnion) AcceptFuncs(asStringFunc func(string) error, asIntegerFunc func(int) error, unknownFunc func(string) error) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in CustomUnion type")
		}
		return unknownFunc(u.typ)
	case "asString":
		if u.asString == nil {
			return fmt.Errorf("field \"asString\" is required")
		}
		return asStringFunc(*u.asString)
	case "asInteger":
		if u.asInteger == nil {
			return fmt.Errorf("field \"asInteger\" is required")
		}
		return asIntegerFunc(*u.asInteger)
	}
}

func (u *CustomUnion) AsStringNoopSuccess(_ string) error {
	return nil
}

func (u *CustomUnion) AsIntegerNoopSuccess(_ int) error {
	return nil
}

func (u *CustomUnion) ErrorOnUnknown(typeName string) error {
	return fmt.Errorf("invalid value in union type. Type name: %s", typeName)
}

func (u *CustomUnion) Accept(v CustomUnionVisitor) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknown(u.typ)
	case "asString":
		if u.asString == nil {
			return fmt.Errorf("field \"asString\" is required")
		}
		return v.VisitAsString(*u.asString)
	case "asInteger":
		if u.asInteger == nil {
			return fmt.Errorf("field \"asInteger\" is required")
		}
		return v.VisitAsInteger(*u.asInteger)
	}
}

type CustomUnionVisitor interface {
	VisitAsString(v string) error
	VisitAsInteger(v int) error
	VisitUnknown(typeName string) error
}

func (u *CustomUnion) AcceptWithContext(ctx context.Context, v CustomUnionVisitorWithContext) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknownWithContext(ctx, u.typ)
	case "asString":
		if u.asString == nil {
			return fmt.Errorf("field \"asString\" is required")
		}
		return v.VisitAsStringWithContext(ctx, *u.asString)
	case "asInteger":
		if u.asInteger == nil {
			return fmt.Errorf("field \"asInteger\" is required")
		}
		return v.VisitAsIntegerWithContext(ctx, *u.asInteger)
	}
}

type CustomUnionVisitorWithContext interface {
	VisitAsStringWithContext(ctx context.Context, v string) error
	VisitAsIntegerWithContext(ctx context.Context, v int) error
	VisitUnknownWithContext(ctx context.Context, typeName string) error
}

func NewCustomUnionFromAsString(v string) CustomUnion {
	return CustomUnion{typ: "asString", asString: &v}
}

func NewCustomUnionFromAsInteger(v int) CustomUnion {
	return CustomUnion{typ: "asInteger", asInteger: &v}
}
