generators:
  testgenerated:
    go-generate-dir: integration_test/testgenerated
    gen-paths:
      paths:
        - integration_test/testgenerated
  conjure-api:
    go-generate-dir: conjure-api
    gen-paths:
      paths:
        - conjure-api
  conjure-graph-testdata:
    go-generate-dir: conjure/graph/testdata
    gen-paths:
      paths:
        - conjure/graph/testdata
  conjure-verifier:
    go-generate-dir: conjure-go-verifier
    gen-paths:
      paths:
        - conjure-go-verifier
