// This file was generated by Conjure and should not be manually edited.

package api

import (
	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
	"github.com/palantir/conjure-go/v6/cj"
	"github.com/palantir/conjure-go/v6/cj/types"
	"github.com/palantir/pkg/binary"
)

type BinaryAlias []byte

func (a BinaryAlias) String() string {
	return binary.New(a).String()
}

func (a BinaryAlias) MarshalText() ([]byte, error) {
	return binary.New(a).MarshalText()
}

func (a *BinaryAlias) UnmarshalText(data []byte) error {
	rawBinaryAlias, err := binary.Binary(data).Bytes()
	if err != nil {
		return err
	}
	*a = rawBinaryAlias
	return nil
}

func (a BinaryAlias) MarshalJSON() ([]byte, error) {
	return json.Marshal(json.MarshalerTo(a))
}

func (a BinaryAlias) MarshalJSONTo(enc *jsontext.Encoder) error {
	return (types.Binary[[]byte]{}).MarshalJSONTo(enc, []byte(a))
}

func (a *BinaryAlias) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, json.UnmarshalerFrom(a))
}

func (a *BinaryAlias) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	return (types.Binary[[]byte]{}).UnmarshalJSONFrom(dec, (*[]byte)(a))
}

func (a BinaryAlias) MarshalYAML() (any, error) {
	return cj.YAMLV3MarshalerFromJSON(a)
}

func (a *BinaryAlias) UnmarshalYAML(unmarshal func(any) error) error {
	return cj.YAMLV3UnmarshalerToJSON(a, unmarshal)
}

type BinaryAliasAlias struct {
	Value *BinaryAlias
}

func (a BinaryAliasAlias) MarshalText() ([]byte, error) {
	if a.Value == nil {
		return nil, nil
	}
	return binary.New(*a.Value).MarshalText()
}

func (a *BinaryAliasAlias) UnmarshalText(data []byte) error {
	rawBinaryAliasAlias, err := binary.Binary(data).Bytes()
	if err != nil {
		return err
	}
	*a.Value = rawBinaryAliasAlias
	return nil
}

func (a BinaryAliasAlias) MarshalJSON() ([]byte, error) {
	return json.Marshal(json.MarshalerTo(a))
}

func (a BinaryAliasAlias) MarshalJSONTo(enc *jsontext.Encoder) error {
	return (types.OptionalMarshaler[*BinaryAlias, BinaryAlias, types.Binary[BinaryAlias]]{}).MarshalJSONTo(enc, a.Value)
}

func (a *BinaryAliasAlias) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, json.UnmarshalerFrom(a))
}

func (a *BinaryAliasAlias) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	return (types.OptionalUnmarshaler[*BinaryAlias, BinaryAlias, types.Binary[BinaryAlias]]{}).UnmarshalJSONFrom(dec, &a.Value)
}

func (a BinaryAliasAlias) MarshalYAML() (any, error) {
	return cj.YAMLV3MarshalerFromJSON(a)
}

func (a *BinaryAliasAlias) UnmarshalYAML(unmarshal func(any) error) error {
	return cj.YAMLV3UnmarshalerToJSON(a, unmarshal)
}

type BinaryAliasOptional struct {
	Value *[]byte
}

func (a BinaryAliasOptional) MarshalText() ([]byte, error) {
	if a.Value == nil {
		return nil, nil
	}
	return binary.New(*a.Value).MarshalText()
}

func (a *BinaryAliasOptional) UnmarshalText(data []byte) error {
	rawBinaryAliasOptional, err := binary.Binary(data).Bytes()
	if err != nil {
		return err
	}
	*a.Value = rawBinaryAliasOptional
	return nil
}

func (a BinaryAliasOptional) MarshalJSON() ([]byte, error) {
	return json.Marshal(json.MarshalerTo(a))
}

func (a BinaryAliasOptional) MarshalJSONTo(enc *jsontext.Encoder) error {
	return (types.OptionalMarshaler[*[]byte, []byte, types.Binary[[]byte]]{}).MarshalJSONTo(enc, a.Value)
}

func (a *BinaryAliasOptional) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, json.UnmarshalerFrom(a))
}

func (a *BinaryAliasOptional) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	return (types.OptionalUnmarshaler[*[]byte, []byte, types.Binary[[]byte]]{}).UnmarshalJSONFrom(dec, &a.Value)
}

func (a BinaryAliasOptional) MarshalYAML() (any, error) {
	return cj.YAMLV3MarshalerFromJSON(a)
}

func (a *BinaryAliasOptional) UnmarshalYAML(unmarshal func(any) error) error {
	return cj.YAMLV3UnmarshalerToJSON(a, unmarshal)
}
