// This file was generated by Conjure and should not be manually edited.

package api

import (
	"encoding/base64"

	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

type CustomObject struct {
	Data        []byte       `json:"data"`
	BinaryAlias *BinaryAlias `json:"binaryAlias"`
}

func (o CustomObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(json.MarshalerTo(o))
}

func (o CustomObject) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	{
		if err := enc.WriteToken(jsontext.String("data")); err != nil {
			return err
		}
		if len(o.Data) > 0 {
			b64out := enc.UnusedBuffer()
			b64out = append(b64out, '"')
			b64out = base64.StdEncoding.AppendEncode(b64out, o.Data)
			b64out = append(b64out, '"')
			if err := enc.WriteValue(b64out); err != nil {
				return err
			}
		} else {
			if err := enc.WriteToken(jsontext.String("")); err != nil {
				return err
			}
		}
	}
	if o.BinaryAlias != nil {
		if err := enc.WriteToken(jsontext.String("binaryAlias")); err != nil {
			return err
		}
		optVal := *o.BinaryAlias
		if len([]byte(optVal)) > 0 {
			b64out := enc.UnusedBuffer()
			b64out = append(b64out, '"')
			b64out = base64.StdEncoding.AppendEncode(b64out, []byte(optVal))
			b64out = append(b64out, '"')
			if err := enc.WriteValue(b64out); err != nil {
				return err
			}
		} else {
			if err := enc.WriteToken(jsontext.String("")); err != nil {
				return err
			}
		}
	}
	if err := enc.WriteToken(jsontext.EndObject); err != nil {
		return err
	}
	return nil
}

func (o CustomObject) MarshalYAML() (any, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CustomObject) UnmarshalYAML(unmarshal func(any) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}
