// This file was generated by Conjure and should not be manually edited.

package bar

import (
	"github.com/palantir/conjure-go/v6/cycles/testdata/pkg-cycle/conjure/com/palantir/buzz"
	"github.com/palantir/conjure-go/v6/cycles/testdata/pkg-cycle/conjure/com/palantir/foo"
)

type Type3 struct {
	Field1 buzz.Type1 `json:"field1" yaml:"field1"`
	Field2 foo.Type4  `json:"field2" yaml:"field2"`
}
