// This file was generated by Conjure and should not be manually edited.

package api

import (
	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
	"github.com/palantir/conjure-go/v6/cj"
	"github.com/palantir/conjure-go/v6/cj/types"
)

type Struct1 struct {
	Data string `json:"data"`
}

func (o Struct1) MarshalJSON() ([]byte, error) {
	return json.Marshal(json.MarshalerTo(o))
}

func (o Struct1) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	{
		if err := enc.WriteToken(jsontext.String("data")); err != nil {
			return err
		}
		if err := (types.String[string]{}).MarshalJSONTo(o.Data, enc); err != nil {
			return err
		}
	}
	if err := enc.WriteToken(jsontext.EndObject); err != nil {
		return err
	}
	return nil
}

func (o *Struct1) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, json.UnmarshalerFrom(o))
}

func (o *Struct1) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if tok, err := dec.ReadToken(); err != nil {
		return err
	} else if kind := tok.Kind(); kind != '{' {
		return cj.NewKindMismatchError(dec, kind, "opening brace for Struct1")
	}
	var seenData bool
	strict, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers)
	var unknownMembers []string
	for {
		key, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if kind := key.Kind(); kind == '}' {
			break // End of object
		} else if kind != '"' {
			return cj.NewKindMismatchError(dec, kind, "next key or closing brace for Struct1")
		}
		switch key.String() {
		case "data":
			if seenData {
				return cj.NewDuplicateFieldKeyError(dec, "Struct1", "data")
			}
			seenData = true
			if err := (types.String[string]{}).UnmarshalJSONFrom(&o.Data, dec); err != nil {
				return err
			}
		default:
			if strict {
				unknownMembers = append(unknownMembers, key.String())
			}
		}
	}
	var missingFields []string
	if !seenData {
		missingFields = append(missingFields, "data")
	}
	if len(missingFields) > 0 {
		return cj.NewMissingRequiredFieldsError(dec, "Struct1", missingFields)
	}
	if strict && len(unknownMembers) > 0 {
		return cj.NewUnknownFieldsError(dec, "Struct1", unknownMembers)
	}
	return nil
}

func (o Struct1) MarshalYAML() (any, error) {
	return cj.YAMLV3MarshalerFromJSON(o)
}

func (o *Struct1) UnmarshalYAML(unmarshal func(any) error) error {
	return cj.YAMLV3UnmarshalerToJSON(o, unmarshal)
}
