// Code generated by conjure-go. DO NOT EDIT.

//go:build go1.18

package api

import (
	"context"
	"fmt"

	"github.com/palantir/conjure-go/v7/integration_test/testgenerated/imports/pkg1/api"
	api1 "github.com/palantir/conjure-go/v7/integration_test/testgenerated/imports/pkg2/api"
	v2 "github.com/palantir/conjure-go/v7/integration_test/testgenerated/imports/pkg4/v2"
	v21 "github.com/palantir/conjure-go/v7/integration_test/testgenerated/imports/pkg5/v2"
)

type UnionWithT[T any] Union

func (u *UnionWithT[T]) Accept(ctx context.Context, v UnionVisitorWithT[T]) (T, error) {
	var result T
	switch u.typ {
	default:
		if u.typ == "" {
			return result, fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknown(ctx, u.typ)
	case "one":
		if u.one == nil {
			return result, fmt.Errorf("field \"one\" is required")
		}
		return v.VisitOne(ctx, *u.one)
	case "two":
		if u.two == nil {
			return result, fmt.Errorf("field \"two\" is required")
		}
		return v.VisitTwo(ctx, *u.two)
	case "three":
		if u.three == nil {
			return result, fmt.Errorf("field \"three\" is required")
		}
		return v.VisitThree(ctx, *u.three)
	case "four":
		if u.four == nil {
			return result, fmt.Errorf("field \"four\" is required")
		}
		return v.VisitFour(ctx, *u.four)
	}
}

func (u *UnionWithT[T]) AcceptFuncs(oneFunc func(api.Struct1) (T, error), twoFunc func(api1.Struct2) (T, error), threeFunc func(v2.ObjectInPackageEndingInVersion) (T, error), fourFunc func(v21.DifferentPackageEndingInVersion) (T, error), unknownFunc func(string) (T, error)) (T, error) {
	var result T
	switch u.typ {
	default:
		if u.typ == "" {
			return result, fmt.Errorf("invalid value in union type")
		}
		return unknownFunc(u.typ)
	case "one":
		if u.one == nil {
			return result, fmt.Errorf("field \"one\" is required")
		}
		return oneFunc(*u.one)
	case "two":
		if u.two == nil {
			return result, fmt.Errorf("field \"two\" is required")
		}
		return twoFunc(*u.two)
	case "three":
		if u.three == nil {
			return result, fmt.Errorf("field \"three\" is required")
		}
		return threeFunc(*u.three)
	case "four":
		if u.four == nil {
			return result, fmt.Errorf("field \"four\" is required")
		}
		return fourFunc(*u.four)
	}
}

func (u *UnionWithT[T]) OneNoopSuccess(api.Struct1) (T, error) {
	var result T
	return result, nil
}

func (u *UnionWithT[T]) TwoNoopSuccess(api1.Struct2) (T, error) {
	var result T
	return result, nil
}

func (u *UnionWithT[T]) ThreeNoopSuccess(v2.ObjectInPackageEndingInVersion) (T, error) {
	var result T
	return result, nil
}

func (u *UnionWithT[T]) FourNoopSuccess(v21.DifferentPackageEndingInVersion) (T, error) {
	var result T
	return result, nil
}

func (u *UnionWithT[T]) ErrorOnUnknown(typeName string) (T, error) {
	var result T
	return result, fmt.Errorf("invalid value in union type. Type name: %s", typeName)
}

type UnionVisitorWithT[T any] interface {
	VisitOne(ctx context.Context, v api.Struct1) (T, error)
	VisitTwo(ctx context.Context, v api1.Struct2) (T, error)
	VisitThree(ctx context.Context, v v2.ObjectInPackageEndingInVersion) (T, error)
	VisitFour(ctx context.Context, v v21.DifferentPackageEndingInVersion) (T, error)
	VisitUnknown(ctx context.Context, typ string) (T, error)
}
